### ISSUE TITLE
Change "localhost" to my IP

### ISSUE THREAD

**Issue by dlbone** [mikiher/audiobookshelf-windows#14]
In the RSS feed documentation, the feed has the IP address but with the windows version it is set to "localhost" so I can't stream from another podcast app on my local network. Anyway to set this?

**Comment by mikiher** [comment]
I can try to fix this, but right now:
- the server just takes the domain name/ip from the request, which is probably the right thing to do. 
- when you click "Open Audiobookshelf..." in the tray app, it starts the browser with http://localhost:<port>, because I want the browser to access it locally (through the loopback interface) and not pass though the local network. It usually gives you the quickest server response time.
- all of this doesn't preclude from accessing the server through the local network IP. Just replace http://localhost:<port> with http://<your ip>:<port> and save it using a bookmark on your browser. Now, since the RSS feed url takes the host from the request, the feed will be created with your ip as hostname.
- But I think you don't need all of the above. Just change localhost to <your ip> in the feed URL - it will just work.

Given all the above, I don't think I'm going to change anything.

**Comment by mikiher** [comment]
Closing this as "not planned"

**Comment by mikiher** [comment]
Not planned
