### ISSUE TITLE
watcher

### ISSUE THREAD

**Issue by david85091** [mikiher/audiobookshelf-windows#15]
watcher not seeing new audiobooks when uploaded. if i go to settings libraries and scan it will see it then.

**Comment by bantanamera** [comment]
go to settings and enable watcher (Enables the automatic adding/updating of items when file changes are detected. *Requires server restart)

**Comment by david85091** [comment]
it is enabled. I restarted the service and rebooted the server. also this is a windows server 2022. wondering if that makes a difference. with all the updates.

**Comment by mikiher** [comment]
The reason I was asking because the file system watcher will not work for network mapped drives.

If you can put your library on a local drive, the watcher should be working (you will still need to initially perform an initial library scan though, because the watcher will only start after the library is created). 

The warning is normal, you can ignore it.

**Comment by david85091** [comment]
its kind of a hassle to move them back. i loose all the metadata to the books. what a pain to reset. maybe this can get fixed in another release. i think i may just keep pushing scan when i upload an audiobook. which is all i am using it for right now. i use calibre-web for books. but i like the way this does audiobooks better. it doesnt have good options for metadata for some books. and i dont see any way to have the program get the covers for non published books. like pdf. but i do like this program. and cant wait to see what it becomes.

**Comment by mikiher** [comment]
You still have the option to set up an automatic library scan every x minutes/hours.

I understand the need for a tool that automatically migrates a library and its metadata from one location to another. It was actually [one of the first bugs](#3) opened for windows version, since there are users who would like to migrate their old Docker Windows installation to this native installation, but are currently unable to do it without re-scanning.

I'm going to work on that tool soon.

**Comment by david85091** [comment]
good idea didnt think about autoscan
