### ISSUE TITLE
Update prompt issue

### ISSUE THREAD

**Issue by jaykup26** [mikiher/audiobookshelf-windows#17]
Audiobookshelf-windows seems to check for updates periodically, but keeps stacking those update prompts.

Can this be fixed to only appears once, or have an option to auto update without prompt?

![image](https://github.com/mikiher/audiobookshelf-windows/assets/628881/240a6647-9603-49e7-a3f3-8d1ce7ab80d5)

Versions:
![image](https://github.com/mikiher/audiobookshelf-windows/assets/628881/9def09b9-8d0c-4828-8d7a-042b837b681e)
![image](https://github.com/mikiher/audiobookshelf-windows/assets/628881/153b54d2-995a-467f-9f9a-7a80b6305261)

Thank you

**Comment by mikiher** [comment]
Thanks for reporting this.

I'm on vacation until the end of the week, I'll work on a fix after that.

**Comment by mikiher** [comment]
OK, this is now fixed in [this commit](https://github.com/mikiher/audiobookshelf-windows/commit/a200ebab901e04c320e09123a5561022cbe44af2). The message will now appear only once (it will still check for updates, but any old un-dismissed message will be dismissed, so only one message will appear).

At this point in time I still don't want to automatically update without any prompting - this may come in a future release.

The fix will be released in the next update (which you **will** need to install... :)
