### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by theboo** [mikiher/audiobookshelf-windows#7]
Going from 2.7.1 to 2.7.2 through the auto update system worked perfectly.

Going from 2.7.2 to 2.7.2.1 it just keeps saying there's a new update available. In "about audiobookshelf server" it says I'm on 2.7.2. Even after going through the update process multiple times.

Outside of this, I've been using your windows builds for almost a month now, been super solid, thank you so much for your work! Brought me back to abs lol.

**Comment by mikiher** [comment]
Sorry about this.
My build process is still a bit clunky and the version number did not get updated correctly in the installer, so the program still thinks you're on an older version.
Will fix this right away.

**Comment by mikiher** [comment]
OK, I re-published a fixed [release v2.7.2.1](https://github.com/mikiher/audiobookshelf-windows/releases/tag/v2.7.2.1)
If you update now to the new version, you should not see those update messages any more after that.
Please let me know if you encounter any additional issues.
Thanks for reporting the bug!

**Comment by colvdv** [comment]
I noticed I was having this issue so I downloaded v2.7.2.1 and ran the .exe installer, installed it, and ran audiobookshelf again but nothing appears to have changed. Still showing that I am running v2.7.2, latest 2.8.0. I also right-clicked on the tray icon and checked for updates but no updates found.

**Comment by mikiher** [comment]
I have not yet released v2.8.0 of the windows installer, so there are no updates yet (planning to do so today - it is a somewhat special release, since it's moving from node 16 to 20, and some manual intervention is required). If you want me to help with your other issues, please attach the log file as requested (on the other bug). 

If you're worried about exposing your log file on the bug, you can attach it to an email to audiobookshelf.windows@gmail.com. I assure you I will only use it for debugging purposes.

**Comment by colvdv** [comment]
Thank you for getting back to me. I wondered if that was the case after posting.

As far as my other issue I am waiting for it to happen again so that I can pull a fresh log for you. Thank you.

**Comment by mikiher** [comment]
The Server Logs UI shows only the last run's log, but the log file should
(if you have not manually deleted it) contain logs from previous runs that
crashed - so there's no need to wait for another one to happen again.
